name: Build

on:
  pull_request:
    paths-ignore:
      - "**.md"
      - "mod/**"
  push:
    paths-ignore:
      - "**.md"
      - "mod/**"
  workflow_call:
    inputs:
      ref:
        description: "Reference passed to `actions/checkout` to checkout the repo"
        type: string
        default: ""

permissions:
  contents: read

jobs:
  build:
    strategy:
      # Don't abort when one combination fails.
      fail-fast: false
      matrix:
        os: [win, linux]
        arch: [64, 32]
        configuration: [release]
        include:
          - os: win
            runner: windows-latest
          - os: linux
            runner: ubuntu-latest

    runs-on: ${{ matrix.runner }}

    steps:
      - name: Install 32-bit libs
        if: ${{ matrix.os == 'linux' && matrix.arch == 32 }}
        run: >
          sudo apt-get install
          g++-multilib

      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref }}

      - name: Build solution
        uses: ./.github/actions/build
        with:
          preset: ${{ matrix.os }}${{ matrix.arch }}.${{ matrix.configuration }}
